# Generated by Django 5.0.4 on 2024-05-03 18:23

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.PositiveIntegerField(default=0)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(default=None, max_length=250)),
                ('catergory', models.CharField(choices=[('AB', 'Abaya'), ('JI', 'Jilbaab'), ('Niq', 'Niqab'), ('Hi', 'Hijaab'), ('DR', 'Dress')], default=None, max_length=20)),
                ('images', models.FileField(default=None, upload_to='images/')),
                ('in_stock', models.BooleanField(default=True)),
                ('by_protect_fee', models.BooleanField(default=False)),
            ],
        ),
    ]
