# Generated by Django 5.0.4 on 2024-04-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_user_username_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
