# Generated by Django 5.0.4 on 2024-04-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
